### ISSUE TITLE
is pretrained model broken ?

### ISSUE THREAD

**Issue by ixtiyoruz** [FangGet/tf-monodepth2#1]
when i run the command : 
**python train_monodepth2.py train config/monodepth2_kitti.yml ./model/pretrained_model/model.latest**
 
i am getting the error :

_Traceback (most recent call last):
  File "train_monodepth2.py", line 51, in <module>
    _cli_test(config, output_dir, args)
  File "train_monodepth2.py", line 25, in _cli_test
    monodepth2_learner.test(output_dir)
  File "C:\Users\essys\Desktop\project_1\depth_estimation\tf-monodepth2-master\tf-monodepth2-master\model\monodepth2_learner.py", line 371, in test
    self.saver.restore(sess, latest_ckpt)
  File "C:\Users\essys\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1274, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None._

**Comment by FangGet** [comment]
Sorry for late reply, have you solved this problem? I will have a try on it.

**Comment by ixtiyoruz** [comment]
I haven't tried since, did you update the model ?

**Comment by FangGet** [comment]
@ixtiyoruz I just have a try. and soory, it's my fault, you need to add a checkpoint txt file to tell tensorflow which model you decide to use, example like that:
filename: checkpoint (no extension)
file detail:
model_checkpoint_path: "/YOUR/PATH/TO/pretrained_model/model.latest"

put this file inside pretrained_model directory and everything will be ok.

**Comment by ixtiyoruz** [comment]
Sorry for late reply, Ok, Thank you.
