### ISSUE TITLE
why did this normalization

### ISSUE THREAD

**Issue by sunnyHelen** [FangGet/tf-monodepth2#12]
https://github.com/FangGet/tf-monodepth2/blob/533b735400d3ecbbd25c30efdacf4a4a2bb73330/model/monodepth2_learner.py#L26

Hi, thanks for you contribution for the tf implementation. I want to know why did you do this normalization.
I am writing my own version of monodepth2 too. But it seems there's something wrong. The loss can converge, but the test result can only achieve abs rel 0.152. Can you provide some suggestion about my situation?

**Comment by FangGet** [comment]
For numeric stability.
