### ISSUE TITLE
Error when trying to train

### ISSUE THREAD

**Issue by abeyang00** [FangGet/tf-monodepth2#2]
I get such error when i try to train with KITTI dataset.

![Screenshot from 2019-09-24 13-57-11](https://user-images.githubusercontent.com/36392866/65482235-4f374a00-ded3-11e9-83ba-85083dd329c2.png)

Do you know what's causing this error?

**Comment by FangGet** [comment]
It seems that you have not prepared training data correctly.
Did you run the prepare prepare_train_data.py to generate training data and set the training data root directory into config file(monodepth2_kitti.yml)

**Comment by abeyang00** [comment]
@FangGet yes i have done both, resulting images after prepare_train_data.py should be 384x416 right? Each image contains 3 consecutive images like shown below

![Screenshot from 2019-09-25 11-03-06](https://user-images.githubusercontent.com/36392866/65563296-13a88880-df84-11e9-9a79-5e8d8917b347.png)

I have also modified kitti_raw_loader.py where you should scipy.misc to read and resize images. Since they are deprecated, i'm currently using PIL library. should that be a problem?

**Comment by FangGet** [comment]
Nope, generally we use following three size:
416\*128，640\*192，1024\*320

Note that 416，640， 1024 is the width, we need to kepp the ratio for raw image as much as possible

**Comment by abeyang00** [comment]
@FangGet I have used prepare_train_data.py as provided. The preset image size is 416x128. So if you concatenate three of the images, shouldn't it be 416*384? I made no modifications to prepare_train_data.py so i don't know what went wrong there

**Comment by FangGet** [comment]
Your width and height seems mutual exchanged. 
![0000000003](https://user-images.githubusercontent.com/11433213/65564286-f8874a00-df7e-11e9-8550-1e4bde3b958f.jpg)
This is the image I generated use prepare_train_data.py

**Comment by abeyang00** [comment]
Thank you! this solved the problem.
