### ISSUE TITLE
Getting Depth to points in the image.

### ISSUE THREAD

**Issue by vineeth2309** [FangGet/tf-monodepth2#7]
How would you obtain the depth to all points in the image using the output of the model?
Does it involve using the camera intrinsics, or is there a way to directly obtain depth?

**Comment by FangGet** [comment]
the output of the model is a so called inverse depth map, real depth value calculate code, see:
https://github.com/FangGet/tf-monodepth2/blob/533b735400d3ecbbd25c30efdacf4a4a2bb73330/utils/tools.py#L27

camera intrinsics are used to compute pointcloud for global map.

**Comment by vineeth2309** [comment]
Does the disparity to depth function output the distance in meter to every point? Also would I just use the camera intrinsic matrix to convert to camera coordinates and then use the depth of each pixel to plot the point cloud directly, or is any pose transformation required?

**Comment by FangGet** [comment]
disp_to_depth output the distance in meter, but with scale factor between predicted and groundtruth.
use camera intrinsics, you can reproject pixel coordinates into camera coordinate system, then use predicted pose to get pointcloud in world coordiante system.
```
Pcam = K^-1 [u,v,d]^T
```
```
Pworld = Twc * Pcam
```

**Comment by vineeth2309** [comment]
Is there an example code that outputs both the pose and the disparity image of the model simultaneously?
I could only find them separately.
Or is Twc just the translation and rotation of axes between what I consider world and camera?

**Comment by FangGet** [comment]
First of all, Twc is a 3x4 or 4x4(homogeneous) matrix presenting transformation from camera to world, the pose network output axis rotation and translation, you need a transform like : 
https://github.com/FangGet/tf-monodepth2/blob/533b735400d3ecbbd25c30efdacf4a4a2bb73330/utils/tools.py#L170

There is no demo for both depth and pose output but it's easy to code one. I'm busy working on another project and have little time to do that so please refer to 
https://github.com/FangGet/tf-monodepth2/blob/533b735400d3ecbbd25c30efdacf4a4a2bb73330/model/monodepth2_learner.py#L406
and add pose part to get both.

**Comment by vineeth2309** [comment]
So i would use the same encoder and eval over both the pose decoder and depth decoder?

**Comment by FangGet** [comment]
set keyword "build_type" in monodepth2_learner.py to "both", then both depth and pose network will be constructed, next what you need to do is construct input for both depth and pose network, and get corresponding output for depth and pose.

**Comment by vineeth2309** [comment]
Is there no way to obtain the point locations without the pose transformation? I am having a slight issue with understanding the input and output dimension for the pose network.

**Comment by FangGet** [comment]
The directly pointcloud output for network is out of the purpose of this project, monodepth2 is tend to predict depth map for current image and visual odometry for sequencial images. With these information along with camera intrinsics, pointcloud can actually be obtained using 3d geometry theory.

for geometry information, refer to book "Multiple view geometry in computer vision"

**Comment by vineeth2309** [comment]
Just a final clarification, the function disparity to depth outputs depth in meters in the camera coordinate system right?

**Comment by FangGet** [comment]
it‘s depth, you know, depth in pixel coordinate like common rgbd camera output, please tell it from pointcloud
