### ISSUE TITLE
How to test my own images?

### ISSUE THREAD

**Issue by NovaMind-Z** [FangGet/tf-monodepth2#8]
Hi, 
Thanks for your brilliant work! Could you tell me how to test my own image for a generalization task? I mean how to preprocess my own picture. Do I just need resize the shape to (640,192) and use your test code?
And I still feel puzzled about these three line code in the model/ monodepth2_learner.py 
![image](https://user-images.githubusercontent.com/42997811/73860524-a46a6b80-4876-11ea-8b8a-e3e827162c8f.png), do these two matrices circled by the red have the same size? I try to run the test code and find there is a bug when concatenating the two matrices.

Thanks in advance for your reply.

**Comment by FangGet** [comment]
Sorry for late reply, the code you circled is just a format of data struct, used to test both depth and pose, if you onlu need to get depth result, please refer to line: https://github.com/FangGet/tf-monodepth2/blob/533b735400d3ecbbd25c30efdacf4a4a2bb73330/model/monodepth2_learner.py#L419

for your question for image size, yes, you need to resize your input image into (640, 192), this step can also be found in former reference code.
